apiVersion: v2
name: bankobserve360
description: BankObserve360 — full-stack banking observability training platform
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: BankObserve360 Team

dependencies:
  - name: core-banking
    version: 1.0.0
    repository: file://../charts/core-banking
    condition: core-banking.enabled
  - name: payments
    version: 1.0.0
    repository: file://../charts/payments
    condition: payments.enabled
  - name: retail-banking
    version: 1.0.0
    repository: file://../charts/retail-banking
    condition: retail-banking.enabled
  - name: customer-identity
    version: 1.0.0
    repository: file://../charts/customer-identity
    condition: customer-identity.enabled
  - name: fraud-risk
    version: 1.0.0
    repository: file://../charts/fraud-risk
    condition: fraud-risk.enabled
  - name: notifications
    version: 1.0.0
    repository: file://../charts/notifications
    condition: notifications.enabled
  - name: audit-compliance
    version: 1.0.0
    repository: file://../charts/audit-compliance
    condition: audit-compliance.enabled
  - name: legacy-stack
    version: 1.0.0
    repository: file://../charts/legacy-stack
    condition: legacy-stack.enabled
  - name: observability-stack
    version: 1.0.0
    repository: file://../charts/observability-stack
    condition: observability-stack.enabled
  - name: loadrunner
    version: 1.0.0
    repository: file://../charts/loadrunner
    condition: loadrunner.enabled
  - name: fault-injector
    version: 1.0.0
    repository: file://../charts/fault-injector
    condition: fault-injector.enabled
