-- Oracle XE init: BANKOBS_CORE schema
-- Runs once on container start (gvenzl/oracle-xe mounts /container-entrypoint-initdb.d).

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER BANKOBS_CORE IDENTIFIED BY "Training123!"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE,
      CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO BANKOBS_CORE;

ALTER SESSION SET CURRENT_SCHEMA = BANKOBS_CORE;

-- ── Tables ──────────────────────────────────────────────────────────────────
CREATE TABLE BANKOBS_CORE.ACCOUNTS (
  account_id    VARCHAR2(20) PRIMARY KEY,
  customer_id   VARCHAR2(20) NOT NULL,
  account_type  VARCHAR2(10) NOT NULL,
  balance       NUMBER(18,2) DEFAULT 0,
  status        VARCHAR2(10) DEFAULT 'ACTIVE',
  branch_code   VARCHAR2(6),
  ifsc          VARCHAR2(11),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_ACCOUNTS_CUSTOMER ON BANKOBS_CORE.ACCOUNTS(customer_id);
CREATE INDEX IDX_ACCOUNTS_BRANCH   ON BANKOBS_CORE.ACCOUNTS(branch_code);
CREATE INDEX IDX_ACCOUNTS_STATUS   ON BANKOBS_CORE.ACCOUNTS(status);

CREATE TABLE BANKOBS_CORE.TRANSACTIONS (
  txn_id        VARCHAR2(36) PRIMARY KEY,
  account_id    VARCHAR2(20),
  txn_type      VARCHAR2(10) NOT NULL,
  amount        NUMBER(18,2) NOT NULL,
  currency      VARCHAR2(3) DEFAULT 'INR',
  status        VARCHAR2(10) NOT NULL,
  reference_no  VARCHAR2(50),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  channel       VARCHAR2(20),
  CONSTRAINT FK_TXN_ACCOUNT FOREIGN KEY (account_id) REFERENCES BANKOBS_CORE.ACCOUNTS(account_id)
);
CREATE INDEX IDX_TXN_ACCOUNT ON BANKOBS_CORE.TRANSACTIONS(account_id, created_at DESC);
CREATE INDEX IDX_TXN_REF     ON BANKOBS_CORE.TRANSACTIONS(reference_no);
CREATE INDEX IDX_TXN_CHANNEL ON BANKOBS_CORE.TRANSACTIONS(channel, created_at DESC);

CREATE TABLE BANKOBS_CORE.CUSTOMERS (
  customer_id    VARCHAR2(20) PRIMARY KEY,
  name_token     VARCHAR2(36),
  dob_masked     VARCHAR2(10),
  pan_masked     VARCHAR2(10),
  aadhaar_masked VARCHAR2(14),
  mobile_masked  VARCHAR2(15),
  email_masked   VARCHAR2(50),
  risk_category  VARCHAR2(10) DEFAULT 'LOW',
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE BANKOBS_CORE.GL_ENTRIES (
  entry_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id    VARCHAR2(20),
  debit_amount  NUMBER(18,2) DEFAULT 0,
  credit_amount NUMBER(18,2) DEFAULT 0,
  narration     VARCHAR2(200),
  posting_date  DATE DEFAULT SYSDATE,
  batch_id      VARCHAR2(36),
  CONSTRAINT FK_GL_ACCOUNT FOREIGN KEY (account_id) REFERENCES BANKOBS_CORE.ACCOUNTS(account_id)
);
CREATE INDEX IDX_GL_ACCOUNT ON BANKOBS_CORE.GL_ENTRIES(account_id, posting_date DESC);
CREATE INDEX IDX_GL_BATCH   ON BANKOBS_CORE.GL_ENTRIES(batch_id);

CREATE TABLE BANKOBS_CORE.BRANCHES (
  branch_id   VARCHAR2(6) PRIMARY KEY,
  branch_name VARCHAR2(100) NOT NULL,
  ifsc        VARCHAR2(11) UNIQUE NOT NULL,
  city        VARCHAR2(50),
  state       VARCHAR2(50),
  zone        VARCHAR2(20)
);

COMMIT;
